# Étape 1 : Build Angular
FROM node:18 AS build
WORKDIR /app

# Copier uniquement les fichiers nécessaires pour installer les dépendances
COPY package*.json ./
RUN npm install

# Copier le reste du projet (sans node_modules)
COPY . .

# Builder Angular
RUN npm run build --prod

# Étape 2 : Servir avec Nginx
FROM nginx:alpine
COPY --from=build /app/dist/angular /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
